# Priority Labels.
- name: P0
  description: High priority - needs immediate attention
  color: ff0000  # bright red
- name: P1
  description: Medium priority - address after P0 items
  color: 0052cc  # bright blue