name: Sync Repo Settings

on:
  # Run manually.
  workflow_dispatch:
  
  push:
    branches:
      - master
      - HelpersTask248_Find_a_way_to_keep_GitHub_repos_in_sync
  
  schedule:
    - cron: 0 0 * * *

jobs:
  repo_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repo Settings
        uses: kbrashears5/github-action-repo-settings-sync@v3.0.0
        with:
          REPOSITORIES: |
            causify-ai/sports_analytics
            causify-ai/tutorials
          ALLOW_ISSUES: 'true'
          ALLOW_PROJECTS: 'true'
          ALLOW_WIKI: 'true'
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
